import { Injectable } from '@nestjs/common';

export interface TemplateVariables {
  [key: string]: string;
}

@Injectable()
export class EmailTemplatesService {
  getWelcomeEmail(variables: TemplateVariables) {
    const { name, company = 'Wanago' } = variables;

    return {
      subject: `Welcome to ${company}, ${name}!`,
      text: `Hi ${name},\n\nWelcome to ${company}! We're excited to have you on board.\n\nBest regards,\nThe ${company} Team`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; }
            .container { max-width: 600px; margin: 0 auto; }
            .header { background: #4F46E5; color: white; padding: 20px; text-align: center; }
            .content { padding: 30px; background: #f9f9f9; }
            .footer { padding: 20px; text-align: center; color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>Welcome to ${company}!</h1>
            </div>
            <div class="content">
              <h2>Hello ${name},</h2>
              <p>We're thrilled to welcome you to ${company}!</p>
              <p>Your account has been successfully created and you can now access all features.</p>
              <p>If you have any questions, feel free to reach out to our support team.</p>
              <br>
              <p>Best regards,<br>The ${company} Team</p>
            </div>
            <div class="footer">
              <p>This is an automated message. Please do not reply to this email.</p>
              <p>© ${new Date().getFullYear()} ${company}. All rights reserved.</p>
            </div>
          </div>
        </body>
        </html>
      `,
    };
  }

  getPasswordResetEmail(variables: TemplateVariables) {
    const { name, resetLink, company = 'Our App' } = variables;

    return {
      subject: `Password Reset Request - ${company}`,
      text: `Hi ${name},\n\nYou requested to reset your password. Click the link below to proceed:\n\n${resetLink}\n\nIf you didn't request this, please ignore this email.\n\nBest regards,\nThe ${company} Team`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; }
            .container { max-width: 600px; margin: 0 auto; }
            .button { background: #4F46E5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; display: inline-block; }
          </style>
        </head>
        <body>
          <div class="container">
            <h2>Password Reset</h2>
            <p>Hello ${name},</p>
            <p>You requested to reset your password for ${company}.</p>
            <p>Click the button below to reset your password:</p>
            <p><a href="${resetLink}" class="button">Reset Password</a></p>
            <p>If the button doesn't work, copy and paste this link:</p>
            <p><small>${resetLink}</small></p>
            <p>If you didn't request this, please ignore this email.</p>
            <br>
            <p>Best regards,<br>The ${company} Team</p>
          </div>
        </body>
        </html>
      `,
    };
  }

  getScheduledReportEmail(variables: TemplateVariables) {
    const {
      reportName,
      reportDate,
      downloadLink,
      company = 'Our App',
    } = variables;

    return {
      subject: `Your ${reportName} Report - ${reportDate}`,
      text: `Here is your scheduled ${reportName} report for ${reportDate}.\n\nDownload link: ${downloadLink}\n\nBest regards,\n${company} Reports Team`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; }
            .report-card { border: 1px solid #ddd; padding: 20px; margin: 20px 0; border-radius: 8px; }
          </style>
        </head>
        <body>
          <h2>${reportName} Report</h2>
          <p>Date: ${reportDate}</p>
          <div class="report-card">
            <h3>Report Summary</h3>
            <p>Your scheduled report is ready for download.</p>
            <a href="${downloadLink}">Download Report</a>
          </div>
          <p>This is an automated report generated by ${company}.</p>
        </body>
        </html>
      `,
    };
  }
}
